version: '3.9'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    volumes:
      - my-db:${MOUNTED_SHARED_DIRECTORY}/lib/mysql
volumes:
  my-db: