version: '3.8'
services:
    flask:
        image: webapp-flask
        build:
            context: ./server
            dockerfile: dockerfile-flask
        expose:
            - ${FLASK_PORT}
        environment:
          FLASK_PORT: ${FLASK_PORT}
        volumes:
            - "./server/:/app/server"
            - "./server/client/:/app/client"
    nginx:
        image: webapp-nginx
        build:
            context: ./server
            dockerfile: dockerfile-nginx
        environment:
          FLASK_PORT: ${FLASK_PORT}
          NGINX_EXPOSE_PORT: ${NGINX_EXPOSE_PORT}
        ports:
            - ${FLASK_PORT}:${NGINX_EXPOSE_PORT}
        depends_on:
            - flask