version: '3.8'
services:
    flask:
        image: webapp-flask
        build:
            context: ./server
            dockerfile: dockerfile-flask
        volumes:
            - "./server/:/app/server"
            - "./server/client/:/app/client"
    nginx:
        image: webapp-nginx
        build:
            context: ./server
            dockerfile: dockerfile-nginx
        ports:
            - 5000:80
        depends_on:
            - flask